version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:5173
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://ory-kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/welcome
  allowed_return_urls:
    - http://localhost:5173
    - http://localhost:4455
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://localhost:4455/recovery
      use: code

    verification:
      enabled: false # Change this to true to allow verification flows
      ui_url: http://localhost:4455/verification
      use: code
      after:
        default_browser_return_url: http://localhost:4455/welcome

    logout:
      after:
        default_browser_return_url: http://localhost:4455/login

    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m
      after:
        default_browser_return_url: http://localhost:5173

    registration:
      lifespan: 10m
      ui_url: http://localhost:4455/registration
      after:
        default_browser_return_url: http://localhost:5173
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
            - hook: web_hook
              config:
                url: http://host.docker.internal:3000/webhooks/ory/after-signup
                method: POST # HTTP method used to send request to the webhook URL.
                # Encoded Jsonnet template used to render payload.
                # Originally taken from here:
                # https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#customizing-request-body-with-jsonnet
                # The updated version is under config/kratos/webhook_payload.jsonnet
                body: base64://ZnVuY3Rpb24oY3R4KSB7DQogIHVzZXJJZDogY3R4LmlkZW50aXR5LmlkLA0KICB0cmFpdHM6IHsNCiAgICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbCwNCiAgICBuYW1lOiBjdHguaWRlbnRpdHkudHJhaXRzLm5hbWUsDQogIH0sDQp9
                response:
                  ignore: false # Defines if the webhook response should be ignored and run async. Boolean. OPTIONAL
                  parse: false # Defines if the webhook response should be parsed and interpreted. Boolean. OPTIONAL
                auth:
                  type: api_key
                  config:
                    name: Authorization
                    value: super-secret-ory-webhook-key # TODO: Edit this file/put in env vars
                    in: header # alternatively "cookie"

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

feature_flags:
  use_continue_with_transitions: true
