services:
  # Infra services
  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres
  litellm:
    extends:
      file: docker-compose.common.yml
      service: litellm
  mongo:
    extends:
      file: docker-compose.common.yml
      service: mongo
  chroma:
    extends:
      file: docker-compose.common.yml
      service: chroma
  vector-admin:
    extends:
      file: docker-compose.common.yml
      service: vector-admin
  ory-kratos-migrate:
    extends:
      file: docker-compose.common.yml
      service: ory-kratos-migrate
  ory-kratos:
    extends:
      file: docker-compose.common.yml
      service: ory-kratos
  ory-kratos-admin-ui:
    extends:
      file: docker-compose.common.yml
      service: ory-kratos-admin-ui
  ory-kratos-self-serve-ui:
    extends:
      file: docker-compose.common.yml
      service: ory-kratos-self-serve-ui
  vault:
    extends:
      file: docker-compose.common.yml
      service: vault
  # App services
  api:
    extends:
      file: docker-compose.common.yml
      service: api
    image: ghcr.io/merlinn/api:latest
  slackbot:
    extends:
      file: docker-compose.common.yml
      service: slackbot
    image: ghcr.io/merlinn/slackbot:latest
  data-processor:
    extends:
      file: docker-compose.common.yml
      service: data-processor
    image: ghcr.io/merlinn/data-processor:latest
  dashboard:
    extends:
      file: docker-compose.common.yml
      service: dashboard
    image: ghcr.io/merlinn/dashboard:latest