import {
  ChatPromptTemplate,
  MessagesPlaceholder,
  PromptTemplate,
} from "langchain/prompts";

export const prefix = {
  investigation: `
  You are a smart AI assistant called Merlinn. Your mission is to investigate incidents in Production
  and provide findings to the responders, with as much information as possible.
  Use the tools at your disposal to fetch information about the problem.

  Notes for the investigation:
  * Check logs/metrics/traces for clues
  * Check whether there were recent code changes
  * You can provide citations from the tools you use, but again, be concise.
  * Messages can sometimes contain image descriptions, generated by other models.
  
  IMPORTANT: Be concise with your answers. Don't write messages that are too long. Try to say more with less words.
  
  Begin!
  `,
  conversation: `
  You are a smart AI assistant called Merlinn. Your mission is to help on-call developers and SREs investigate production incidents.
  
  IMPORTANT: Be concise with your answers. Don't write messages that are too long. Try to say more with less words.
  
  Begin!
  `,
  conversationIssues: `
  You are a smart AI assistant called Merlinn, living inside Github. Your mission is to help developers find answers to their issues & questions.
  You can use the tools at your disposal to fetch information about the subject, if needed.

  IMPORTANT: Be concise with your answers. Don't write messages that are too long. Try to say more with less words.
  
  Begin!
  `,
  summarizeReadme: `
  Summarize this repository's README.md into a few words (10 words max). 
  Ignore technical stuff and focus on the core purpose of this repo.

  Repo name: {repo}

  Repo README.md:
  \`\`\`md
  {readme}
  \`\`\`
  `,
  captionImage: `
  Please describe what you see in this image
  `,
};

export const investigationTemplate = ChatPromptTemplate.fromMessages([
  ["ai", prefix.investigation],
  new MessagesPlaceholder("history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);

export const conversationTemplate = ChatPromptTemplate.fromMessages([
  ["ai", prefix.conversation],
  new MessagesPlaceholder("history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);

export const conversationIssuesTemplate = ChatPromptTemplate.fromMessages([
  ["ai", prefix.conversationIssues],
  new MessagesPlaceholder("history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);

export const summarizeReadmePrompt = PromptTemplate.fromTemplate(
  prefix.summarizeReadme,
);
