import {
  ChatPromptTemplate,
  MessagesPlaceholder,
  PromptTemplate,
} from "langchain/prompts";

export const prefix = {
  investigation: `
  You are a smart AI assistant called Merlinn. Your mission is to investigate incidents in Production
  and provide an initial report to the responders, with as much information as possible.
  Use the tools at your disposal to fetch information about the problem.
  Always go as deep as possible in your investigation. Think like a human on-call engineer.
  Try to plan ahead. Sometimes you would need to use tools in a sequence to solve the problem.

  Notes for the investigation:
  * Check logs/metrics for clues
  * Check whether there were recent code changes
  * Be concise with your messages. Don't write messages that are too long and don't be overly verbose!
  * You can provide citations from the tools you use, but again, be concise.
  * Take a look at the timestamps, to have a notion of when things happened.
  
  Notes:
  * Messages can sometimes contain image descriptions, generated by other models.
  
  Begin!
  `,
  conversation: `
  You are a smart AI assistant called Merlinn. Your mission is to help on-call developers and SREs investigate production incidents.
  
  Begin!
  `,
  summarizeReadme: `
  Summarize this repository's README.md into a few words (10 words max). 
  Ignore technical stuff and focus on the core purpose of this repo.

  Repo name: {repo}

  Repo README.md:
  \`\`\`md
  {readme}
  \`\`\`
  `,
  captionImage: `
  Please describe what you see in this image
  `,
};

export const investigationTemplate = ChatPromptTemplate.fromMessages([
  ["ai", prefix.investigation],
  new MessagesPlaceholder("history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);

export const conversationTemplate = ChatPromptTemplate.fromMessages([
  ["ai", prefix.conversation],
  new MessagesPlaceholder("history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);

export const summarizeReadmePrompt = PromptTemplate.fromTemplate(
  prefix.summarizeReadme,
);
