#########################
###  LLM Setup file  ####
#########################

# In order to use vespper, you need to provide 2 models: chat model and an embedding model. Our Opensource version supports OpenAI's models.
# You must keep the naming convention of the model_list as it is. Namely, model_name: chat-model and model_name: embedding-model

model_list:
  ###  OpenAI is the current supported model, reach our to us for more support ####
  - model_name: chat-model
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: embedding-model
    litellm_params:
      model: text-embedding-3-large
      api_key: os.environ/OPENAI_API_KEY
      dimensions: 3072
