FROM node:18.18.2-alpine as base

WORKDIR /app

# Add package file
COPY package.json ./
COPY yarn.lock ./

# Install deps
RUN yarn install

# Copy source
COPY src ./src
COPY tsconfig.json ./tsconfig.json

EXPOSE 3000

# Run watch command
CMD ["yarn", "run", "watch"]
